language: php
php:
  - "hhvm-nightly"
  - "5.6"
  - "5.4"
  - "5.3"
install:
  - composer install
  - npm install
script:
  - composer test
  - npm test
notifications:
  irc:
    channels:
      - "chat.freenode.net##krinkle"
