sudo: false
language: php
php:
  - "hhvm"
  - "5.6"
  - "5.5"
install:
  - composer install
  - npm install
script:
  - composer test
  - npm test
notifications:
  irc:
    channels:
      - "chat.freenode.net##krinkle"
